from fun1 import gto
from fun2 import cehltofahr
from fun3 import solve
from fun4 import filter_prime
from fun5 import perms
from fun6 import reverse
from fun7 import has_33
from fun8 import spy_game
from fun9 import vol
from fun10 import unique
from fun11 import palindrome
from fun12 import histo